services:
  - type: web
    name: file-converter
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production